'use client'

import dynamic from 'next/dynamic'
import { useState } from 'react'
import { Bell, Car, Check, ChevronLeft, CircleDollarSign, Clock3, MapPin, Menu, Navigation, Star, ToggleRight, TrendingUp, X } from 'lucide-react'
import { mockDrivers, mockPassengers } from '@/lib/mockData'

const Map = dynamic(() => import('@/components/Map/LeafletMap').then((m) => m.LeafletMap), { ssr: false, loading: () => <div className="h-full bg-[#dbe8e5] flex items-center justify-center">جاري تحميل الخريطة...</div> })

export default function DriverPage() {
  const [online, setOnline] = useState(true)
  const [accepted, setAccepted] = useState(false)
  const driver = mockDrivers[0]
  const passenger = mockPassengers[0]
  return <main className="min-h-screen bg-[#f7f9fc]">
    <header className="h-20 bg-[#0b2553] text-white flex items-center justify-between px-5 lg:px-10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-[#f5b800] flex items-center justify-center"><Car className="text-[#0b2553]"/></div><div><b className="text-xl">وصلني</b><p className="text-xs text-blue-200">لوحة السائق</p></div></div><div className="flex items-center gap-5"><button className="p-2"><Bell size={20}/></button><div className="flex items-center gap-2"><img src={driver.avatar} alt={driver.name} className="w-9 h-9 rounded-full bg-white/20"/><span className="font-semibold">{driver.name}</span></div><Menu className="md:hidden"/></div></header>
    <div className="max-w-7xl mx-auto p-5 lg:p-8"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-7"><div><p className="text-primary font-semibold text-sm">الأربعاء، 03 سبتمبر 2026</p><h1 className="text-3xl font-bold mt-1">مرحباً، {driver.name.split(' ')[0]}</h1></div><button onClick={() => setOnline(!online)} className={`flex items-center gap-3 px-5 py-3 rounded-xl font-bold ${online ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-secondary text-muted-foreground'}`}><span className={`w-3 h-3 rounded-full ${online ? 'bg-green-500' : 'bg-gray-400'}`}/>{online ? 'أنت متصل الآن' : 'أنت غير متصل'}<ToggleRight size={22}/></button></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-7">{[{label:'أرباح اليوم',value:'580.00 ر.س',icon:CircleDollarSign,color:'text-green-600'},{label:'رحلات اليوم',value:'12 رحلة',icon:Navigation,color:'text-primary'},{label:'ساعات العمل',value:'6 س 25 د',icon:Clock3,color:'text-yellow-600'},{label:'تقييمك',value:'4.9 / 5',icon:Star,color:'text-orange-500'}].map((stat) => { const Icon=stat.icon; return <div key={stat.label} className="bg-card rounded-2xl p-4 border shadow-sm"><Icon className={`${stat.color} mb-3`} size={22}/><p className="text-xs text-muted-foreground">{stat.label}</p><p className="font-bold text-lg mt-1">{stat.value}</p></div>})}</div>
      <div className="grid lg:grid-cols-[1.5fr_1fr] gap-6"><div className="bg-card rounded-2xl border overflow-hidden min-h-[440px]"><div className="p-5 flex justify-between items-center"><div><h2 className="font-bold text-lg">الخريطة</h2><p className="text-sm text-muted-foreground">موقعك الحالي والطلبات القريبة</p></div><span className="flex items-center gap-2 text-sm text-green-600"><span className="w-2 h-2 bg-green-500 rounded-full"/> متصل</span></div><div className="h-[355px]"><Map center={driver.currentLocation}/></div></div>
      <div className="space-y-5"><div className="bg-card rounded-2xl border p-5"><div className="flex items-center justify-between mb-4"><h2 className="font-bold text-lg">طلب رحلة جديد</h2><span className="text-xs bg-yellow-100 text-yellow-700 px-2 py-1 rounded-full">جديد</span></div>{!accepted ? <><div className="flex items-center gap-3 mb-5"><img src={passenger.avatar} alt={passenger.name} className="w-12 h-12 rounded-full bg-secondary"/><div><b>{passenger.name}</b><p className="text-sm text-muted-foreground">4.8 <Star size={12} fill="currentColor" className="inline text-yellow-500"/></p></div><b className="mr-auto">25 ر.س</b></div><div className="space-y-3 text-sm mb-5"><p className="flex gap-3"><span className="w-2 h-2 rounded-full bg-primary mt-2"/>{'حي النخيل، شارع الملك فهد'}</p><p className="flex gap-3"><MapPin size={16} className="text-yellow-600"/>{'مركز الرياض التجاري'}</p></div><div className="flex gap-2"><button onClick={() => setAccepted(true)} className="flex-1 bg-primary text-white rounded-xl py-3 font-bold flex justify-center gap-2"><Check size={18}/> قبول الطلب</button><button className="px-4 rounded-xl bg-secondary text-muted-foreground"><X size={18}/></button></div></> : <div className="text-center py-8"><div className="w-14 h-14 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-3"><Check/></div><b>تم قبول الرحلة</b><p className="text-sm text-muted-foreground mt-1">توجه إلى موقع الراكب</p><button className="mt-5 w-full rounded-xl bg-primary text-white py-3 font-bold">بدء الرحلة</button></div>}</div><div className="bg-card rounded-2xl border p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-bold">أداء هذا الأسبوع</h2><TrendingUp className="text-green-600" size={19}/></div><div className="flex items-end gap-2 h-24">{[35,55,42,75,60,88,70].map((height,i)=><div key={i} className="flex-1 bg-blue-100 rounded-t-md relative" style={{height:`${height}%`}}><div className="absolute inset-x-0 bottom-0 bg-primary rounded-t-md h-1/2"/></div>)}</div><div className="flex justify-between text-[10px] text-muted-foreground mt-2"><span>السبت</span><span>الأحد</span><span>الإثنين</span><span>الثلاثاء</span><span>الأربعاء</span></div></div></div></div></div>
  </main>
}
