'use client'

import dynamic from 'next/dynamic'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, CarFront, CheckCircle2, Clock3, CreditCard, MapPin, MessageCircle, Phone, ShieldCheck, Star } from 'lucide-react'
import { mockDrivers, mockPassengers, mockRides } from '@/lib/mockData'
const Map = dynamic(() => import('@/components/Map/LeafletMap').then((m) => m.LeafletMap), { ssr: false })

export default function RideDetailsPage() { const router = useRouter(); const driver = mockDrivers[0]; const ride = mockRides[0]; const [accepted, setAccepted] = useState(false)
return <main className="passenger-app"><header className="passenger-header"><button aria-label="العودة" onClick={() => router.back()} className="icon-button"><ArrowRight size={19}/></button><div className="brand-lockup"><div className="brand-mark"><CarFront size={22}/></div><div><strong>تك توكي</strong><small>TUKTUKY</small></div></div><span className="rides-header-title">تفاصيل الرحلة</span></header><section className="details-layout"><div className="details-map"><Map pickup={ride.pickup} dropoff={ride.dropoff} center={ride.pickup.coordinates} route/></div><div className="details-panel"><div className="panel-eyebrow">الرحلة رقم #{ride.id.toUpperCase()}</div><h1>تفاصيل رحلتك</h1><div className="live-status"><span/><b>السائق متاح وقريب منك</b><small>يصل خلال 3 دقائق</small></div><div className="driver-profile"><img src={driver.avatar} alt={driver.name}/><div><b>{driver.name}</b><span><Star size={13} fill="currentColor"/> {driver.rating} ({driver.reviewCount} تقييم)</span><small>{driver.carModel} · {driver.carColor} · {driver.carPlate}</small></div><div className="driver-contact"><button aria-label="اتصال"><Phone size={17}/></button><button aria-label="رسالة"><MessageCircle size={17}/></button></div></div><div className="details-route"><div className="route-row"><i className="route-point pickup"/><span><small>نقطة الانطلاق</small><b>{ride.pickup.address}</b></span></div><div className="route-line"/><div className="route-row"><i className="route-point dropoff"/><span><small>الوجهة</small><b>{ride.dropoff.address}</b></span></div></div><div className="fare-box"><div><small>التكلفة المتوقعة</small><strong>{ride.estimatedFare} ج.م</strong></div><div><small>طريقة الدفع</small><span><CreditCard size={15}/>المحفظة</span></div></div><div className="safety-note"><ShieldCheck size={20}/><span><b>رحلتك محمية</b><small>تم التحقق من بيانات السائق والمركبة</small></span></div><button className="gold-button" onClick={() => setAccepted(!accepted)}>{accepted ? <><CheckCircle2 size={18}/>تم تأكيد الرحلة</> : 'تأكيد طلب الرحلة'}</button><button className="cancel-link" onClick={() => router.push('/passenger')}>{accepted ? 'العودة للرئيسية' : 'إلغاء والعودة'}</button></div></section></main> }
