'use client'

import { useRouter } from 'next/navigation'
import { ArrowRight, Car, CheckCircle2, MapPin, Star } from 'lucide-react'
import { mockDrivers, mockPassengers } from '@/lib/mockData'

export default function RideDetailsPage() {
  const router = useRouter()
  const driver = mockDrivers[0]
  const passenger = mockPassengers[0]

  return <main className="min-h-screen bg-background"><header className="flex h-20 items-center gap-4 border-b bg-card px-5 lg:px-10"><button aria-label="العودة" onClick={() => router.push('/passenger')} className="rounded-lg p-2 hover:bg-secondary"><ArrowRight size={20} /></button><div><p className="font-bold text-xl text-primary">تفاصيل الرحلة</p><p className="text-xs text-muted-foreground">مراجعة بيانات السائق والوجهة</p></div></header><section className="mx-auto max-w-2xl p-5 lg:p-10"><div className="mb-6 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><img src={driver.avatar} alt={driver.name} className="h-14 w-14 rounded-full bg-secondary" /><div><h1 className="text-xl font-bold">{driver.name}</h1><p className="mt-1 text-sm text-muted-foreground">{driver.carModel} · {driver.carColor}</p></div></div><span className="flex items-center gap-1 text-yellow-600"><Star size={17} fill="currentColor" />{driver.rating}</span></div><div className="mt-6 flex items-center gap-3 rounded-xl bg-green-50 p-4 text-green-700"><CheckCircle2 size={20} /><span className="text-sm font-semibold">السائق متاح الآن وقريب منك</span></div></div><div className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="mb-5 font-bold">تفاصيل المسار</h2><div className="space-y-5"><div className="flex gap-3"><span className="mt-1 h-3 w-3 rounded-full bg-primary ring-4 ring-blue-100" /><div><p className="text-xs text-muted-foreground">نقطة الانطلاق</p><p className="font-semibold">حي النخيل، شارع الملك فهد</p></div></div><div className="mr-1 h-5 border-r-2 border-dashed border-primary/30" /><div className="flex gap-3"><MapPin className="text-yellow-600" size={18} /><div><p className="text-xs text-muted-foreground">الوجهة</p><p className="font-semibold">مركز الرياض التجاري</p></div></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-secondary p-4"><p className="text-xs text-muted-foreground">الراكب</p><p className="mt-1 font-semibold">{passenger.name}</p></div><div className="rounded-xl bg-secondary p-4"><p className="text-xs text-muted-foreground">السعر التقديري</p><p className="mt-1 font-bold text-primary">25 ر.س</p></div></div><button onClick={() => router.push('/passenger')} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-primary-foreground hover:opacity-90"><Car size={19} /> تأكيد الرحلة</button></div></section></main>
}
